spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://116.89.191.47:6544/niadb
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    batch-size: 2000
    hikari:
      max-lifetime: 30000
      idle-timeout: 6000
      maximum-pool-size: 5
      pool-name: 'nia-pool'

client:
  base-url: "http://localhost:5050"
  connect-timeout-ms: 3000
  read-timeout-ms: 5000

