version: '3.8'

services:
  web:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - webnet

  was:
    build:
      context: ./BE
      dockerfile: Dockerfile
    environment:
      - |
        JAVA_OPTS=-Dserver.port=8080 \
        -Dspring.profiles.active=pubdev
      - SERVER_PORT=8080
      - AJP_PORT=8009
    ports:
      - "8080:8080"
      - "8009:8009"
    networks:
      - webnet
    depends_on:
      - web

networks:
  webnet:
