server:
  port: 8095

logging:
  level:
    root: INFO

---
#
# 개발
#
spring:
  profiles: dev
  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  logging:
    config: classpath:context/logback-spring.xml

  rabbitmq:
    address: 192.168.0.241  #개발
    port: 5672
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineExchange: nia.exchangeEngineDirectly
    engineQueue: nia.EngineIndexDirectly
    engineRoutingKey: nia.EngineIndexDirectly

  cluster:
    timeCondition: 8000
    delay: 30000

  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.241:6544/niadb #개발
    username: ENC(neWOZ5Yxv8OGF2c46X/5X2ha0+vz8+lF)
    password: ENC(j/f3Lz4BetPLn0W3K/KdnpO86dcHeRft)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
#
# 운영
#

spring:
  profiles: real
  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  logging:
    config: classpath:context/logback-spring.xml

  rabbitmq:
    address: 116.89.191.47
    port: 6786
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineExchange: nia.exchangeEngineDirectly
    engineQueue: nia.EngineIndexDirectly
    engineRoutingKey: nia.EngineIndexDirectly


  cluster:
    timeCondition: 8000
    delay: 30000


  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://116.89.191.47:6544/niadb
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true
