server:
  port: 8070
  compression:
      enabled: true
      excluded-user-agents:
      mime-types: application/json,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
      min-response-size: 2048
  tomcat.max-http-form-post-size: 5GB
  tomcat.max-swallow-size: 5GB
  servlet.session.timeout: 30m

  error:
    include-exception: true
    include-stacktrace: always
    path: '/error'
    whitelabel:
      enabled: false

spring:
  application.name: core-web
  config.use-legacy-processing: true  # 스프링 부트 2.4 이전 레거시 구동방식 유지
  main.allow-bean-definition-overriding: true
  profiles.active: dev

  servlet.multipart:
    max-file-size: 5GB
    max-request-size: 5GB

  h2:
    console:
      enabled: true
      settings.web-allow-others: true
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;BUILTIN_ALIAS_OVERRIDE=1;
    username: sa
    password:
    hikari: 
      connectionTimeout: 600000
      maximumPoolSize: 20
      maxLifetime: 600000
      minimumIdle: 10
      validationTimeout: 30000
      idleTimeout: 300000
    # enabled: true

  datasource2nd:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@incodej-lab.iptime.org:1522/xe
    username: NMSSTAT
    password: 463-1 
    dataSource-name: DSANAL
    enabled: true

  datasource3rd:
  #   driver-class-name: oracle.jdbc.driver.OracleDriver
  #   url: jdbc:oracle:thin:@10.22.136.11:1521/KTNMSMON
  #   username: NMSMON
  #   password: 463-1 
  #   dataSource-name: DSMON1
    enabled: false  

  datasource4th:
    enabled: false  

  datasource5th:
    enabled: false  

  redis:
    embedded-server-start: true
    enabled: false
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    maxheap: 128M

  rabbitmq:
    enabled: false  # 접속 불가 환경을 위해 추가함

  jwt:
    secret: jwtsecret12#$
  #sql.init.encoding: UTF-8 # DB 한글이 깨질 경우에만 설정

myconf:
  project: core
  websocket:
    enabled: true   #websocket.enabled
    url: /ws-stomp
    heartbeat.enabled: false
    auth-same-network: true
  auth:
    use: true #auth.use
    otp: 
      use: false #otp.use
  
file:
  access-Url: /external/**

# Log4j2 보안취약점 대응 (version 2.10 ~ 2.14.1)
log4j2.formatMsgNoLookups: true

# https://springdoc.org/#properties
springdoc:
  #  packagesToScan: package1, package2
  pathsToMatch: /**
  override-with-generic-response: false
  swagger-ui:
    doc-expansion: none


