spring:
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://116.89.191.47:6544/niadb
      username: ENC(tD78wIra2l5konGYTRXMepLI/gooXj9NI2Mhc+ss0HJ0VNUMvqJtuzZaAnpTwfyE)
      password: ENC(bVuAREvWcarcjlP/Clu1pKJhQqIzs0+Qk4lLnpmJCc/0bYqGCGcgZNJO588n2yl6)
      batch-size: 2000
      hikari:
        max-lifetime: 30000
        idle-timeout: 6000
        maximum-pool-size: 5
        pool-name: 'nia-pool'

  rabbitmq:
    address: 116.89.191.47
    port: 6786
    username: ENC(tD78wIra2l5konGYTRXMepLI/gooXj9NI2Mhc+ss0HJ0VNUMvqJtuzZaAnpTwfyE)
    password: ENC(bVuAREvWcarcjlP/Clu1pKJhQqIzs0+Qk4lLnpmJCc/0bYqGCGcgZNJO588n2yl6)

    mbaAiModelExchange: nia.exchangeMbaAiModelDirectly
    mbaAiModelQueue: nia.MbaAiModelIndexDirectly
    mbaAiModelRoutingKey: MbaAiModelIndexDirectly

  ems:
    roadm_d_ip: 61.252.53.34
    port_mmc: 42001
    port_evt: 42002
    id: datalake
    pw: korennoc!
#    id: admin
#    pw: ktroadm123