logging:
  level:
    root: INFO
  config: classpath:logback-config-spring.xml

server:
  port: 6803

spring:
  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: real