server:
  port: 8080
  servlet:
    context-path:
    
  
spring:
  profiles:
    active: test
    dev: false

  rabbitmq:
    niaEngineToUi: TEST_MQ_Queue1 # 2024.05.20 운영서버 알람을 가져오지 않기 위한 임시 설정

myconf:
  api-server:
    
file:
  upload-dir: ./external

