server:
  port: 8070
  servlet:
    context-path:

spring:
  profiles:
    active: oper
    dev: false

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  sql:
    init:
      platform: postgres
      encoding: UTF-8

  rabbitmq:
    enabled: true
    address: 116.89.191.47 # incodej-lab.iptime.org
    port: 6786

myconf:
  ssh:
    host: 116.89.191.47
    port: 16891
    user: codej8888
    password: zhfps!
  api-server:
    ipsdn: http://203.255.249.31:8088
  aimonitor-Url: http://116.89.191.45:82
  servermonitor-Url: http://116.89.191.40:3000
  snapshot-Url: http://116.89.191.35:24888/download/

file:
  upload-dir: ./external
