server:
  port: 8070

spring:
  profiles:
    active: devdev
    dev: false

  datasource2nd:
    enabled: true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://incodej-lab.iptime.org:41544/niadb?allowMultiQueries=true
    username: postgres
    password: zhemwpdl12!@
    dataSource-name: niadb
    mapper-packages: >
      com.codej.nia.mapper.db2nd,
      com.codej.nia.test.dao,

  rabbitmq:
    enabled: true
    address: incodej-lab.iptime.org
    port: 41072
    username: niaadmin
    password: niaadmin12#$
    niaEngineToUi: nia.EngineToUiIndexDirectly
    niaUiToEngine: nia.UiToEngineIndexDirectly
    InspectorToUID: OPER#nia.InspectorToUIDirectly
    TicketRestart: OPER#nia.NiaTicketReStartIndexDirectly
