// import { getApiData } from '@/utils'
import http from '@/min/http'
import { AppOptions } from '@/class/appOptions'
// import { apiGetObjectFromJsonFile2 } from '@/api/json-file'
const { debug, isProd } = AppOptions.instance

export const filePath = __filename.replace(/\\/g, '/')

export const ipmsModelApis = {
  viewListCrtIPMst: { desc: 'IP 블록관리 조회', url: '/ipmgmt/createmgmt/viewListCrtIPMst' },
  viewListAsgnIPMst: { desc: 'IP 배정 조회', url: '/ipmgmt/assignmgmt/viewListAsgnIPMst' },
  viewListUnAssignIP: { desc: 'IP 미배정 조회', url: '/ipmgmt/assignmgmt/viewListUnAssignIP' },
  viewDetailSummary: { desc: '라우팅 중복상세 조회', url: '/ipmgmt/assignmgmt/viewDetailSummary' },
  viewCheckTacsIpBlock: { desc: 'IP블럭 중복체크', url: '/opermgmt/tacsmgmt/viewCheckTacsIpBlock' },
  viewListIpAllocMst: { desc: 'IP할당 목록 조회', url: '/ipmgmt/allocmgmt/viewListIpAllocMst' },
  viewDetailAlcIPMst: { desc: 'IP할당 상세정보', url: '/ipmgmt/allocmgmt/viewDetailAlcIPMst' },
  // viewInsertAlcIPMst: { desc: 'IP할당처리 POP', url: '/ipmgmt/allocmgmt/viewInsertAlcIPMst' },
  viewSearchtNeMst: { desc: 'IP할당 > 시설 정보 조회 POP', url: '/ipmgmt/allocmgmt/viewSearchtNeMst' },
  viewSearchtLnMst: { desc: 'IP할당 > 링크 정보 조회 POP', url: '/ipmgmt/allocmgmt/viewSearchtLnMst' },
  viewInsertDivAsgnIPMst: { desc: '배정/할당 > IP분할 대상정보', url: '/ipmgmt/assignmgmt/viewInsertDivAsgnIPMst' },
  viewInsertMrgAsgnIPMst: { desc: '배정/할당 > IP병합 대상정보', url: '/ipmgmt/assignmgmt/viewInsertMrgAsgnIPMst' },
  deletAlcIPMst: { desc: 'IP할당 해지', url: '/ipmgmt/allocmgmt/deletAlcIPMst' },
  viewListSvcStat: { desc: 'IP 서비스별 통계 조회', url: '/statmgmt/ipstatmgmt/viewListSvcStat' },
  viewListOrgSvcStat: { desc: 'IP 조직서비스별 통계 조회', url: '/statmgmt/ipstatmgmt/viewListOrgSvcStat' },
  viewListBlockSizeStat: { desc: 'IP 블록크기별 통계 조회', url: 'statmgmt/ipstatmgmt/viewListBlockSizeStat' },
  viewListIntgrmSvcStat: { desc: 'IP주소 라우팅 비교/점검 통계 조회', url: '/statmgmt/ipstatmgmt/viewListIntgrmSvcStat' },
  viewListIpAllocMstByMain: { desc: 'IP 블록 정보 조회', url: '/ipmgmt/allocmgmt/viewListIpAllocMstByMain' },
  viewListMultiIpInfo: { desc: 'IP 블록 정보 조회(multi)', url: '/ipmgmt/allocmgmt/viewListMultiIpInfo' },
  viewDetailIpAllocMstByMain: { desc: 'IP 블록 상세정보', url: '/ipmgmt/allocmgmt/viewDetailIpAllocMstByMain' },
  viewListIpHistoryMst: { desc: 'IP 이력관리 조회', url: '/ipmgmt/historymgmt/viewListIpHistoryMst' },
  viewDetailIpHistMst: { desc: 'IP 이력 상세정보', url: '/ipmgmt/historymgmt/viewDetailIpHistMst' },
  viewDetailWhois: { desc: 'whois 상세정보', url: '/linkmgmt/socketmgmt/viewDetailWhois' },
  viewDetailSubSvcMst: { desc: '회선 상세조회', url: '/ipmgmt/allocmgmt/viewDetailSubSvcMst' },
  viewListRoutChkMst: { desc: 'IP주소 라우팅 비교/점검 조회', url: '/ipmgmt/routmgmt/viewListRoutChkMst' },
  viewPopInsertAlcIPMst: { desc: 'IP주소 라우팅 비교/점검 > IP할당', url: '/ipmgmt/routmgmt/viewPopInsertAlcIPMst' },
  viewDetailRoutChkMst: { desc: 'IP주소 라우팅 비교/점검 > IP블록 상세 정보', url: '/ipmgmt/routmgmt/viewDetailRoutChkMst' },
  viewDetailNextHop: { desc: 'IP주소 라우팅 비교/점검 > 링크/시설/회선 상세 정보', url: '/ipmgmt/routmgmt/viewDetailNextHop' },
  viewDetailRoutExcptMst: { desc: 'IP주소 라우팅 비교/점검 > 예외처리 상세', url: '/ipmgmt/routmgmt/viewDetailRoutExcptMst' },
  viewPopRoutChkExceptMst: { desc: 'IP주소 라우팅 비교/점검 > 예외처리 관리(예외처리유형)', url: '/ipmgmt/routmgmt/viewPopRoutChkExceptMst' },
  viewPopRoutServiceChkMst: { desc: 'IP주소 라우팅 비교/점검 > IP블록 (해지 후) 분할/병합 처리 전 서비스 변경 작업 ', url: '/ipmgmt/routmgmt/viewPopRoutServiceChkMst' },
  viewPopRoutChkMst: { desc: 'IP주소 라우팅 비교/점검 > 라우팅 수집/DB 비교 처리 POP', url: '/ipmgmt/routmgmt/viewPopRoutChkMst' },
  viewListIpLinkMst: { desc: '운용정보관리(링크) 조회', url: '/ipmgmt/linkmgmt/viewListIpLinkMst' },
  viewDetailIPLinkMst: { desc: '운용정보관리(링크) 상세조회', url: '/ipmgmt/linkmgmt/viewDetailIPLinkMst' },
  viewUpdateIPLinkMst: { desc: '운용정보관리(링크) 수정POP', url: '/ipmgmt/linkmgmt/viewUpdateIPLinkMst' },
  viewListIpHostMst: { desc: '운용정보관리(시설) 조회', url: '/ipmgmt/hostmgmt/viewListIpHostMst' },
  viewDetailIPHostMst: { desc: '운용정보관리(시설) 상세조회', url: '/ipmgmt/hostmgmt/viewDetailIPHostMst' },
  viewIpUploadMst: { desc: 'Upload관리 조회', url: '/ipmgmt/ipuploadmgmt/viewIpUploadMst' },
  viewDetailIpMst: { desc: 'Upload관리 상세조회', url: '/ipmgmt/ipuploadmgmt/viewDetailIpMst' },
  viewListNotice: { desc: '공지사항 리스트', url: '/opermgmt/boardmgmt/viewListNotice' },
  viewDetailNotice: { desc: '공지사항 상세정보', url: '/opermgmt/boardmgmt/viewDetailNotice' },
  viewDetailUnAssignIP: { desc: 'IP 미배정 상세정보', url: '/ipmgmt/assignmgmt/viewDetailUnAssignIP' },
  viewDetailCrtIPMst: { desc: 'IP 블록관리 상세정보 ', url: '/ipmgmt/createmgmt/viewDetailCrtIPMst' },
  viewInsertNotice: { desc: '공지사항 등록 화면 ', url: '/opermgmt/boardmgmt/viewInsertNotice' },
  viewUpdateNotice: { desc: '공지사항 수정 화면 ', url: '/opermgmt/boardmgmt/viewUpdateNotice' },
  viewInsertCrtIPMst: { desc: 'IP 블록 생성 상세모달(신규,추가) ', url: '/ipmgmt/createmgmt/viewInsertCrtIPMst' },
  viewUpdateAsgnIPMst: { desc: 'IP 블록관리 > IP배정 대상정보', url: '/ipmgmt/assignmgmt/viewUpdateAsgnIPMst' },
  viewDetailAsgnIPMst: { desc: 'IP배정 상세정보', url: '/ipmgmt/assignmgmt/viewDetailAsgnIPMst' },
  viewListNode: { desc: 'IP주소 노드 이전 신청 조회', url: '/opermgmt/nodemgmt/viewListNode' },
  viewDetailNode: { desc: 'IP주소 노드 이전 상세', url: '/opermgmt/nodemgmt/viewDetailNode' },
  viewCancelNode: { desc: 'IP주소 노드 이전 반려', url: '/opermgmt/nodemgmt/viewCancelNode' },
  confirmNode: { desc: 'IP주소 노드 이전 승인', url: '/opermgmt/nodemgmt/confirmNode' },
  viewInsertNode: { desc: 'IP주소 노드 이전 신청 > 신청 상세, IP 주소 조회', url: '/opermgmt/nodemgmt/viewInsertNode' },
  viewfnSelectNode: { desc: 'IP주소 노드 이전 신청 > 조회 결과 선택', url: '/opermgmt/nodemgmt/viewfnSelectNode' },
  viewListAssignApyTxn: { desc: 'IP 배정 신청 조회', url: '/opermgmt/assignmgmt/viewListAssignApyTxn' },
  viewDetailAssignApyTxn: { desc: 'IP 배정 신청 조회 상세정보', url: '/opermgmt/assignmgmt/viewDetailAssignApyTxn' },
  viewListPrivateAs: { desc: '사설AS 신청 조회', url: '/opermgmt/asmgmt/viewListPrivateAs' },
  viewDetailPrivateAs: { desc: '사설AS 신청 상세정보', url: '/opermgmt/asmgmt/viewDetailPrivateAs' },
  viewListWhoisModReq: { desc: 'Whois 정보 변경 신청 조회', url: '/opermgmt/whoismgmt/viewListWhoisModReq' },
  viewDetailWhoisModReq: { desc: 'Whois 정보 변경 신청 상세정보', url: '/opermgmt/whoismgmt/viewDetailWhoisModReq' },
  viewRegWhoisModReq: { desc: 'Whois 정보 변경 신청 > 등록 > IP주소 조회', url: '/opermgmt/whoismgmt/viewRegWhoisModReq' },
  viewSearchZipCode: { desc: 'Whois 정보 변경 신청 > 등록 > 주소 검색', url: '/opermgmt/whoismgmt/viewSearchZipCode' },
  viewListReq: { desc: '요구사항 조회', url: '/opermgmt/requiremgmt/viewListReq' },
  viewDetailReq: { desc: '요구사항 조회 상세조회', url: '/opermgmt/requiremgmt/viewDetailReq' },
  // updateReq: { desc: '요구사항 조회 > 수정', url: '/opermgmt/requiremgmt/updateReq' },
  // deleteReq: { desc: '요구사항 조회 > 등록', url: '/opermgmt/requiremgmt/deleteReq' },
  viewListUserAuthSubs: { desc: '사용자 권한 신청 조회', url: '/opermgmt/grantsubsmgmt/viewListUserAuthSubs' },
  viewDetailUserAuthSubs: { desc: '사용자 권한 신청 상세정보', url: '/opermgmt/grantsubsmgmt/viewDetailUserAuthSubs' },
  viewInsertUserAuthSubs: { desc: '사용자 권한 신청 > 등록 화면', url: '/opermgmt/grantsubsmgmt/viewInsertUserAuthSubs' },

  // 운용정보관리(관리자 기능)
  viewListTbBatchSvcBas: { desc: '운용정보관리 > 연동관리 > 배치 연동정보 조회', url: '/linkmgmt/batchmgmt/viewListTbBatchSvcBas' },
  uploadView: { desc: '운용정보관리 > 연동관리 > 우편번호 연동관리', url: '/opermgmt/uploadmgmt/uploadView' },
  viewListBatchHistMst: { desc: '운용정보관리 > 연동관리 > 배치 연동 이력현황', url: '/linkmgmt/batchmgmt/viewListBatchHistMst' },
  viewTacsConnBas: { desc: '운용정보관리 > TACS관리 > TACS 연동정보관리 조회', url: '/opermgmt/tacsmgmt/viewTacsConnBas' },
  viewListTacsFcltMst: { desc: '운용정보관리 > TACS관리 > 조직별 장비 정보관리 조회', url: '/opermgmt/tacsmgmt/viewListTacsFcltMst' },
  viewInsertTacsFcltMst: { desc: '운용정보관리 > TACS관리 > 조직별 장비 정보관리 > 신규생성POP(장비타입 조회)', url: '/opermgmt/tacsmgmt/viewInsertTacsFcltMst' },
  viewListTacsFcltCmdMst: { desc: '운용정보관리 > TACS관리 >  장비별 명령어 정보관리 조회', url: '/opermgmt/tacsmgmt/viewListTacsFcltCmdMst' },
  viewListTacsConnHist: { desc: '운용정보관리 > TACS관리 > TACS 연동 이력현황', url: '/opermgmt/tacsmgmt/viewListTacsConnHist' },
  viewListFcltMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 조직별 장비 정보관리 조회', url: '/opermgmt/intgrmgmt/viewListFcltMst' },
  viewInsertFcltMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 조직별 장비 정보관리 > 신규생성POP(장비타입 조회)', url: '/opermgmt/intgrmgmt/viewInsertFcltMst' },
  viewListFcltCmdMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 장비멸 명령어 정보관리 조회', url: '/opermgmt/intgrmgmt/viewListFcltCmdMst' },
  viewListRoutHistMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 라우팅 연동 이력현황', url: '/opermgmt/intgrmgmt/viewListRoutHistMst' },
  viewListWireMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 유선IP 사전 정보관리 조회', url: '/opermgmt/intgrmgmt/viewListWireMst' },
  viewListMobileMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 조회', url: '/opermgmt/intgrmgmt/viewListMobileMst' },
  viewPopSummaryMst: { desc: 'IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 > 무선IP summary 정보관리 조회', url: '/opermgmt/intgrmgmt/viewPopSummaryMst' },
  viewListOrgBas: { desc: '조직기준 관리 조회', url: '/opermgmt/orgmgmt/viewListOrgBas' },
  viewListTbLvlCdVo: { desc: '계위코드 관리 조회', url: '/opermgmt/orgmgmt/viewListTbLvlCdVo' },
  viewUpdateTbLvlCdVo: { desc: '계위코드 관리 조회 > 수정 화면', url: '/opermgmt/orgmgmt/viewUpdateTbLvlCdVo' },
  viewListLvlBas: { desc: '조직계위 정보관리 조회', url: '/opermgmt/orgmgmt/viewListLvlBas' },
  viewUdateLvlBas: { desc: '조직계위 정보관리 > 조직계위정보 이동 화면', url: '/opermgmt/orgmgmt/viewUdateLvlBas' },
  viewInsertLvlSonMgmtPop: { desc: '조직계위 정보관리 > 오더 노드국 관리 조회 화면', url: '/opermgmt/orgmgmt/viewInsertLvlSonMgmtPop' },
  viewInsertLvlRoleSub: { desc: '조직계위 정보관리 > 시설 수용국 관리 조회 화면', url: '/opermgmt/orgmgmt/viewInsertLvlRoleSub' },
  viewListTbUserBas: { desc: '조직계위 정보관리 > 시설 수용국 관리 조회 화면', url: '/opermgmt/usermgmt/viewListTbUserBas' },
  viewListUserHndSetTxn: { desc: '사용자 정보관리 > 사용자 상세정보 > 사용자 접속 IP변경', url: '/opermgmt/usermgmt/viewListUserHndSetTxn' },
  viewListTbUserConnHist: { desc: '사용자 접속 현황 조회', url: '/opermgmt/usermgmt/viewListTbUserConnHist' },
  viewListUserAuth: { desc: '사용자 권한 관리 조회', url: '/opermgmt/grantmgmt/viewListUserAuth' },
  viewInsertUserAuth: { desc: '사용자 권한 관리 > 권한 정보 등록 화면', url: '/opermgmt/grantmgmt/viewInsertUserAuth' },
  viewListScrnBas: { desc: '화면 관리 조회', url: '/opermgmt/menumgmt/viewListScrnBas' },
  viewDetailScrnBas: { desc: '화면 관리 조회 > 수정 화면', url: '/opermgmt/menumgmt/viewDetailScrnBas' },
  viewListMenuAuth: { desc: '메뉴권한관리 조회', url: '/opermgmt/menumgmt/viewListMenuAuth' },
}
export const ipmsJsonApis = {
  selectAuthCenterList: { desc: '센터 조회', url: '/opermgmt/orgmgmt/selectAuthCenterList' },
  selectAuthNodeList: { desc: '노드 조회', url: '/opermgmt/orgmgmt/selectAuthNodeList' },
  selectOfficeList: { desc: '수용국 조회', url: '/ipmgmt/linemgmt/selectOfficeList' },
  selectSearchLvlCd: { desc: '운용팀 조회', url: 'opermgmt/orgmgmt/selectSearchLvlCd' },
  selectSassignTypeCdList: { desc: '서비스 조회', url: '/ipmgmt/allocmgmt/selectSassignTypeCdList' },
  selectSearchOrgBas: { desc: '운용조직 검색', url: '/opermgmt/orgmgmt/selectSearchOrgBas' },
  //
  appendCrtIPMst: { desc: 'IP 블록관리 > IP 블록생성 > IP 주소 추가', url: '/ipmgmt/createmgmt/appendCrtIPMst' },
  insertListCrtIPMst: { desc: 'IP 블록관리 > IP 블록생성 > IP 주소 등록', url: '/ipmgmt/createmgmt/insertListCrtIPMst' },
  updateCrtIPMst: { desc: 'IP 블록관리  > 수정', url: '/ipmgmt/createmgmt/updateCrtIPMst' },
  updateAsgnIPMst: { desc: 'IP 블록관리 > 배정', url: '/ipmgmt/assignmgmt/updateAsgnIPMst' },
  deleteCrtIPMst: { desc: 'IP 블록관리 삭제', url: '/ipmgmt/createmgmt/deleteCrtIPMst' },
  appendDivAsgnIPMst: { desc: '배정/할당 > IP분할 > 분할 예정 정보 요청', url: '/ipmgmt/assignmgmt/appendDivAsgnIPMst' },
  appendMergeDivAsgnIPMst: { desc: '배정/할당 > IP분할 > 분할 예정 정보 > 병합', url: '/ipmgmt/assignmgmt/appendMergeDivAsgnIPMst' },
  insertListDivAsgnIPMst: { desc: '배정/할당 > IP분할 > 분할 확정 처리', url: '/ipmgmt/assignmgmt/insertListDivAsgnIPMst' },
  allocUpdateAsgnIPMst: { desc: '배정/할당 반납처리', url: '/ipmgmt/allocmgmt/allocUpdateAsgnIPMst' },
  insertMrgAsgnIPMst: { desc: '배정/할당 > 병합처리', url: '/ipmgmt/assignmgmt/insertMrgAsgnIPMst' },
  updateScommentAsgnIPMst: { desc: '할당상세 > 비고수정', url: '/ipmgmt/allocmgmt/updateScommentAsgnIPMst' },
  selectSearchtNeMst: { desc: 'IP할당 > 시설 정보조회', url: '/ipmgmt/allocmgmt/selectSearchtNeMst' },
  selectSearchtLnMst: { desc: 'IP할당 > 링크 정보조회', url: '/ipmgmt/allocmgmt/selectSearchtLnMst' },
  selectDetailSubSvcMstList: { desc: 'IP할당 > 회선 정보조회', url: '/ipmgmt/allocmgmt/selectDetailSubSvcMstList' },
  insertAlcIPMst: { desc: '할당 처리', url: '/ipmgmt/allocmgmt/insertAlcIPMst' },
  insertListExcptMst: { desc: 'IP주소 라우팅 비교/점검 > 예외처리', url: '/ipmgmt/routmgmt/insertListExcptMst' },
  selectCheckService: { desc: 'IP주소 라우팅 비교/점검 > IP블록 (해지 후) 분할/병합 처리 전 서비스 할당 여부 조회', url: '/ipmgmt/routmgmt/selectCheckService' },
  updateServiceMst: { desc: 'IP주소 라우팅 비교/점검 > IP블록 (해지 후) 분할/병합 처리 전 서비스 할당 처리', url: '/ipmgmt/routmgmt/updateServiceMst' },
  insertListIpBlockMatchMst: { desc: 'IP주소 라우팅 비교/점검 > IP블록 (해지 후) 분할/병합 처리', url: '/ipmgmt/routmgmt/insertListIpBlockMatchMst' },
  routInsertListRoutChkMst: { desc: 'IP주소 라우팅 비교/점검 > 라우팅 수집/DB 비교 시작 처리 요청', url: '/ipmgmt/routmgmt/insertListRoutChkMst' },
  confirmNode: { desc: 'IP주소 노드 이전 승인', url: '/opermgmt/nodemgmt/confirmNode' },
  insertLinkIPMst: { desc: '운용정보등록(링크)', url: '/ipmgmt/linkmgmt/insertLinkIPMst' },
  updateLinkIPMst: { desc: '운용정보수정(링크)', url: '/ipmgmt/linkmgmt/updateLinkIPMst' },
  deleteLinkIpMst: { desc: '운용정보삭제(링크)', url: '/ipmgmt/linkmgmt/deleteLinkIPMst' },
  insertHostIPMst: { desc: '운용정보등록(시설)', url: '/ipmgmt/hostmgmt/insertHostIPMst' },
  updateHostIPMst: { desc: '운용정보수정(시설)', url: '/ipmgmt/hostmgmt/updateHostIPMst' },
  deleteHostIPMst: { desc: '운용정보삭제(시설)', url: '/ipmgmt/hostmgmt/deleteHostIPMst' },
  insertNotice: { desc: '공지사항 등록', url: '/opermgmt/boardmgmt/insertNotice' },
  updateNotice: { desc: '공지사항 수정', url: '/opermgmt/boardmgmt/updateNotice' },
  deleteNotice: { desc: '공지사항 삭제', url: '/opermgmt/boardmgmt/deleteNotice' },
  insertNode: { desc: 'IP주소 노드 이전 신청 > 등록', url: '/opermgmt/nodemgmt/insertNode' },
  updateAssignApyTxn: { desc: 'IP 배정신청 상세정보 > 배정, 승인, 반송, 처리내용 수정', url: '/opermgmt/assignmgmt/updateAssignApyTxn' },
  insertAssignApyTxn: { desc: 'IP 배정신청 상세정보 > 배정 신청 등록', url: '/opermgmt/assignmgmt/insertAssignApyTxn' },
  deleteAssignApyTxn: { desc: 'IP 배정신청 상세정보 > 삭제', url: '/opermgmt/assignmgmt/deleteAssignApyTxn' },
  updatePrivateAs: { desc: '사설AS 신청 > 수정', url: '/opermgmt/asmgmt/updatePrivateAs' },
  insertPrivateAs: { desc: '사설AS 신청 > 등록', url: '/opermgmt/asmgmt/insertPrivateAs' },
  selectMinNrequestAsSeq: { desc: '사설AS 신청 > 등록(사설AS 번호 조회)', url: '/opermgmt/asmgmt/selectMinNrequestAsSeq' },
  updateNrequestAsSeqYn: { desc: '사설AS 신청 > 등록, 반려, 반납(TbRequestAsApyTxn 할당처리) ', url: '/opermgmt/asmgmt/updateNrequestAsSeqYn' },
  updateTbRequestAsMst: { desc: '사설AS 신청 > 등록, 반납(TbRequestAsMstVo 할당처리) ', url: '/opermgmt/asmgmt/updateTbRequestAsMst' },
  insertAsHist: { desc: '사설AS 신청 > 할당/반납시 이력저장', url: '/opermgmt/asmgmt/insertAsHist' },
  deletePrivateAs: { desc: '사설AS 신청 > 신청취소 ', url: '/opermgmt/asmgmt/deletePrivateAs' },
  updateWhoisModReqAppr: { desc: 'Whois 정보 변경 신청 > 승인 , 반려 ', url: '/opermgmt/whoismgmt/updateWhoisModReqAppr' },
  viewDeleteWhoisModReq: { desc: 'Whois 정보 변경 신청 > 변경신청취소 ', url: '/opermgmt/whoismgmt/viewDeleteWhoisModReq' },
  viewUpdateWhoisModReqVo: { desc: 'Whois 정보 변경 신청 > 수정 ', url: '/opermgmt/whoismgmt/viewUpdateWhoisModReqVo' },
  selectSearchWhoisInfo: { desc: 'Whois 정보 변경 신청 > 등록 > IP주소 조회 ', url: '/opermgmt/whoismgmt/selectSearchWhoisInfo' },
  sendMail: { desc: 'Whois 정보 변경 신청 > 등록 > 관리자에게 메일 보내기(IP주소) ', url: '/opermgmt/uploadmgmt/sendMail' },
  // insertRegWhoisModReq: { desc: 'Whois 정보 변경 신청 > 변경 신청  ', url: '/opermgmt/uploadmgmt/insertRegWhoisModReq' },
  deleteReq: { desc: '요구사항 삭제', url: '/opermgmt/requiremgmt/deleteReq' },
  insertUserAuthTxnSub: { desc: '사용자 권한 신청 > 등록', url: '/opermgmt/grantsubsmgmt/insertUserAuthTxnSub' },
  // 운용정보관리(관리자 기능)
  updateTbBatchSvcBas: { desc: '운용정보관리 > 연동관리 > 배치 연동 정보 수정', url: '/linkmgmt/batchmgmt/updateTbBatchSvcBas' },
  updateTacsConnBas: { desc: '운용정보관리 > TACS관리 > TACS 연동정보관리 수정', url: '/opermgmt/tacsmgmt/updateTacsConnBas' },
  insertTacsFcltMst: { desc: '운용정보관리 > TACS관리 > 조직별 장비 정보관리 등록', url: '/opermgmt/tacsmgmt/insertTacsFcltMst' },
  updateTacsFcltMst: { desc: '운용정보관리 > TACS관리 > 조직별 장비 정보관리 수정', url: '/opermgmt/tacsmgmt/updateTacsFcltMst' },
  deleteTacsFcltMst: { desc: '운용정보관리 > TACS관리 > 조직별 장비 정보관리 삭제', url: '/opermgmt/tacsmgmt/deleteTacsFcltMst' },
  selectListTacsSfcltTypes: { desc: '운용정보관리 > TACS관리 > 장비별 명령어 정보관리 장비타입 조회', url: '/opermgmt/tacsmgmt/selectListCommonCode' },
  insertTacsFcltCmdMst: { desc: '운용정보관리 > TACS관리 > 장비별 명령어 정보관리 등록', url: '/opermgmt/tacsmgmt/insertTacsFcltCmdMst' },
  updateTacsFcltCmdMst: { desc: '운용정보관리 > TACS관리 > 장비별 명령어 정보관리 수정', url: '/opermgmt/tacsmgmt/updateTacsFcltCmdMst' },
  selectTacsSresultMsg: { desc: '운용정보관리 > TACS관리 > TACS 연동 이력현황 결과메시지 조회', url: '/opermgmt/tacsmgmt/selectSresultMsg' },
  selectListSfcltTypes: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 장비별 명령어 정보관리 장비타입 조회', url: '/opermgmt/intgrmgmt/selectListCommonCode' },
  insertFcltMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 조직별 장비 정보관리 등록', url: '/opermgmt/intgrmgmt/insertFcltMst' },
  updateFcltMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 조직별 장비 정보관리 수정', url: '/opermgmt/intgrmgmt/updateFcltMst' },
  deleteFcltMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 조직별 장비 정보관리 삭제', url: '/opermgmt/intgrmgmt/deleteFcltMst' },
  insertFcltCmdMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 장비별 명령어 정보관리 등록', url: '/opermgmt/intgrmgmt/insertFcltCmdMst' },
  updateFcltCmdMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 장비별 명령어 정보관리 수정', url: '/opermgmt/intgrmgmt/updateFcltCmdMst' },
  deleteFcltCmdMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 장비별 명령어 정보관리 삭제', url: '/opermgmt/intgrmgmt/deleteFcltCmdMst' },
  selectSresultMsg: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 라우팅 연동 이력현황 결과메시지 조회', url: '/opermgmt/intgrmgmt/selectSresultMsg' },
  insertWireMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 유선IP 사전 정보관리 community 등록', url: '/opermgmt/intgrmgmt/insertWireMst' },
  updateWireMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 유선IP 사전 정보관리 수정', url: '/opermgmt/intgrmgmt/updateWireMst' },
  deleteWireMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 유선IP 사전 정보관리 삭제', url: '/opermgmt/intgrmgmt/deleteWireMst' },
  insertMobileMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 community 등록', url: '/opermgmt/intgrmgmt/insertMobileMst' },
  updateMobileMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 수정', url: '/opermgmt/intgrmgmt/updateMobileMst' },
  deleteMobileMst: { desc: '운용정보관리 > IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 삭제', url: '/opermgmt/intgrmgmt/deleteMobileMst' },
  intgrInsertListRoutChkMst: { desc: 'IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 > 무선 전체 라우팅 수집', url: '/opermgmt/intgrmgmt/insertListRoutChkMst' },
  insertMobileSummMst: { desc: 'IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 > Summury관리 > 등록', url: '/opermgmt/intgrmgmt/insertMobileSummMst' },
  deleteMobileSummMst: { desc: 'IP주소 라우팅 비교/점검 > 무선IP 사전 정보관리 > Summury관리 > 삭제', url: '/opermgmt/intgrmgmt/deleteMobileSummMst' },
  updateTbLvlCdVo: { desc: '계위 코드 관리 > 가상 국사 조직 정보 > 수정', url: '/opermgmt/orgmgmt/updateTbLvlCdVo' },
  insertTbLvlCdVo: { desc: '계위 코드 관리 > 가상 국사 조직 정보 > 등록', url: '/opermgmt/orgmgmt/insertTbLvlCdVo' },
  insertValidTbLvlBas: { desc: '조직 계위 정보 관리 > 조직계위등록 > 유효성검사', url: 'opermgmt/orgmgmt/insertValidTbLvlBas' },
  insertTbLvlBas: { desc: '조직 계위 정보 관리 > 조직계위등록 > 등록', url: 'opermgmt/orgmgmt/insertTbLvlBas' },
  validTbLvlBas: { desc: '조직 계위 정보 관리 > 조직계위정보 이동 > 유효성검사', url: 'opermgmt/orgmgmt/validTbLvlBas' },
  updateTbLvlMove: { desc: '조직 계위 정보 관리 > 조직계위정보 이동 > 등록', url: 'opermgmt/orgmgmt/updateTbLvlMove' },
  deleteTbLvlSubCd: { desc: '조직계위 정보관리 > 오더 노드국 관리 > 노드국 목록 삭제', url: '/opermgmt/orgmgmt/deleteTbLvlSubCd' },
  selectSloffice: { desc: '조직계위 정보관리 > 오더 노드국 관리 > 유효성 검사', url: '/opermgmt/orgmgmt/selectSloffice' },
  insertTbLvlSubCd: { desc: '조직계위 정보관리 > 오더 노드국 관리 > 등록', url: '/opermgmt/orgmgmt/insertTbLvlSubCd' },
  deleteLvlRoleSub: { desc: '조직계위 정보관리 > 시설 수용국 관리 > 노드국 목록 삭제', url: '/opermgmt/orgmgmt/deleteLvlRoleSub' },
  insertLvlRoleSub: { desc: '조직계위 정보관리 > 시설 수용국 관리 > 등록', url: '/opermgmt/orgmgmt/insertLvlRoleSub' },
  updateTbUserBas: { desc: '사용자 정보관리 > 수정 > 비밀번호 실패횟수 초기화', url: '/opermgmt/usermgmt/updateTbUserBas' },
  selectSearchTbUserBas: { desc: '사용자 권한 등록 > 운용자 검색 ', url: '/opermgmt/usermgmt/selectSearchTbUserBas' },
  deleteUserAuthTxn: { desc: '사용자 권한 관리> 권한정보 삭제', url: '/opermgmt/grantmgmt/deleteUserAuthTxn' },
  insertUserAuthTxn: { desc: '사용자 권한 관리> 사용자 권한 등록', url: '/opermgmt/grantmgmt/insertUserAuthTxn' },
  insertScrnBas: { desc: '화면관리 > 화면정보 등록', url: '/opermgmt/menumgmt/insertScrnBas' },
  updateScrnBas: { desc: '화면관리 > 화면정보 수정', url: '/opermgmt/menumgmt/updateScrnBas' },
  updateScrnUseYn: { desc: '화면관리 > 사용/미사용 수정', url: '/opermgmt/menumgmt/updateScrnUseYn' },
}

export function apiTest(params) {
  return http({
    url: '/ipmgmt/allocmgmt/viewListIpAllocMst.model',
    method: 'post',
    filePath: filePath,
    data: params || { 'searchBgnDe': '', 'searchCnd': '', 'searchEndDe': '', 'searchWrd': '', 'sortType': 'PIP_PREFIX', 'sortOrdr': 'ASC', 'searchUseYn': '', 'searchBgnCd': '', 'searchEndCd': '', 'pageIndex': 1, 'pageUnit': 10, 'pageSize': 0, 'firstIndex': 1, 'lastIndex': 10, 'recordCountPerPage': 10, 'rowNo': 0, 'typeFlag': '', 'dcreateDt': null, 'screateId': null, 'screateNm': null, 'dmodifyDt': null, 'smodifyId': null, 'smodifyNm': null, 'commonMsg': null, 'screateEmail': null, 'smodifyEmail': null, 'moveType': '', 'moveSearchWrd': '', 'moveSipVersionTypeCd': null, 'url': '/ipmgmt/allocmgmt/viewListIpAllocMst.model', 'menuType': null, 'paramMap': null, 'pipPrefix': null, 'sipVersionTypeCd': 'CV0001', 'sipVersionTypeNm': null, 'sipBlock': null, 'nbitmask': null, 'snetmask': null, 'sfirstAddr': null, 'slastAddr': null, 'nfirstAddr': null, 'nlastAddr': null, 'sfirstIpPreferred': null, 'slastIpPreferred': null, 'sfirstAddrBinary': null, 'slastAddrBinary': null, 'ncnt': null, 'nclassCnt': null, 'nuseIpCnt': null, 'nfreeIpCnt': null, 'nsubnetmask': null, 'ssvcLineTypeCd': 'CL0002', 'ssvcLineTypeNm': null, 'ssvcGroupCd': '', 'ssvcGroupNm': null, 'ssvcObjCd': null, 'ssvcObjNm': null, 'nipBlockMstSeq': null, 'nlvlMstSeq': null, 'nipAssignMstSeq': null, 'nipAllocMstCnt': null, 'sassignLevelCd': '', 'sassignLevelNm': null, 'sipCreateSeqCd': null, 'sipCreateSeqNm': null, 'scomment': null, 'nipmsSvcSeq': null, 'sassignTypeCd': '', 'sassignTypeNm': null, 'sexSvcCd': null, 'sexSvcNm': null, 'sipCreateTypeCd': 'CT0001', 'sipCreateTypeNm': null, 'sipAllocExTypeCd': null, 'sipAllocExTypeNm': null, 'lvlMstSeqListVo': null, 'sllnum': '', 'ssubscnealias': null, 'ssubsclgipportdescription': null, 'sicisofficescode': null, 'sicisofficesname': null, 'sofficecode': '', 'sofficename': null, 'smodelname': null, 'ssubscmstip': null, 'svalidCheck': null, 'sconnAlias': null, 'nipAllocMstSeq': null, 'ssubscnnescode': '', 'ssubscnescode': null, 'sgatewayip': null, 'sneSrchTypeCd': null, 'sicisofficescodeNe': 'XXXXXX', 'ssubscnealiasNe': '', 'smodelnameNe': '', 'ssubscmstipNe': '', 'sssvcMgroupNm': null, 'ssvcLgroupNm': null, 'ssvcUseTypeNm': null, 'ssaid': '', 'scustName': null, 'sipAssignSubNm': null, 'llSrchTypeCd': 'llnum', 'sordernum': '', 'sregyn': null, 'slacpsid': null, 'ssvcUseTypeCd': null, 'sexPushYn': null, 'nticketActSeq': null, 'sipmsSvcNm': null, 'sneossDdYn': null, 'sfirstAddrGwip': null, 'slastAddrGwip': null, 'sAlcSrchTypeCd': null, 'nwhoisSeq': null, 'nroutingChkMstSeq': null, 'pifSerialIp': null, 'sanealias': null, 'samstip': null, 'saifname': null, 'salocationcode': null, 'salocationcodeNm': null, 'saofficescode': null, 'saofficescodeNm': null, 'sznealias': null, 'szmstip': null, 'szifname': null, 'szlocationcode': null, 'szlocationcodeNm': null, 'szofficescode': null, 'szofficescodeNm': null, 'sofficescodeSrch': null, 'snealiasSrch': null, 'smstipSrch': null, 'sifipSrch': null, 'slocationcodeNmSrch': null, 'sllnumSrch': null, 'pifSerialIpSrch': null, 'nipLinkMstSeq': null, 'sconnalias': null, 'sGubun': null, 'sNextHop': null, 'totalCount': 0, 'nsummaryCnt': '', 'snull0Yn': '', 'sintgrmYn': '', 'spageType': null, 'ssubscnealiasType': null, 'bUploadFlag': false, 'sassignTypeCds': null, 'sassignTypeCdMultiStr': '', 'sassignTypeMulti': null, 'ssvcGroupCdMultiStr': '', 'ssvcGroupCdMulti': null, 'ssubsclgipportip': null, 'ssubscrouterserialip': null }
  })
}

export function apiTest2(params) {
  return http({
    url: '/ipmgmt/allocmgmt/viewListIpAllocMst.model',
    method: 'post',
    filePath: filePath,
    data: params || { 'zzz': 'bbb', 'searchBgnDe': '', 'searchCnd': '', 'searchEndDe': '', 'searchWrd': '', 'sortType': 'PIP_PREFIX', 'sortOrdr': 'ASC', 'searchUseYn': '', 'searchBgnCd': '', 'searchEndCd': '', 'pageIndex': 1, 'pageUnit': 10, 'pageSize': 0, 'firstIndex': 1, 'lastIndex': 10, 'recordCountPerPage': 10, 'rowNo': 0, 'typeFlag': '', 'dcreateDt': null, 'screateId': null, 'screateNm': null, 'dmodifyDt': null, 'smodifyId': null, 'smodifyNm': null, 'commonMsg': null, 'screateEmail': null, 'smodifyEmail': null, 'moveType': '', 'moveSearchWrd': '', 'moveSipVersionTypeCd': null, 'url': '/ipmgmt/allocmgmt/viewListIpAllocMst.model', 'menuType': null, 'paramMap': null, 'pipPrefix': null, 'sipVersionTypeCd': 'CV0001', 'sipVersionTypeNm': null, 'sipBlock': null, 'nbitmask': null, 'snetmask': null, 'sfirstAddr': null, 'slastAddr': null, 'nfirstAddr': null, 'nlastAddr': null, 'sfirstIpPreferred': null, 'slastIpPreferred': null, 'sfirstAddrBinary': null, 'slastAddrBinary': null, 'ncnt': null, 'nclassCnt': null, 'nuseIpCnt': null, 'nfreeIpCnt': null, 'nsubnetmask': null, 'ssvcLineTypeCd': 'CL0002', 'ssvcLineTypeNm': null, 'ssvcGroupCd': '', 'ssvcGroupNm': null, 'ssvcObjCd': null, 'ssvcObjNm': null, 'nipBlockMstSeq': null, 'nlvlMstSeq': null, 'nipAssignMstSeq': null, 'nipAllocMstCnt': null, 'sassignLevelCd': '', 'sassignLevelNm': null, 'sipCreateSeqCd': null, 'sipCreateSeqNm': null, 'scomment': null, 'nipmsSvcSeq': null, 'sassignTypeCd': '', 'sassignTypeNm': null, 'sexSvcCd': null, 'sexSvcNm': null, 'sipCreateTypeCd': 'CT0001', 'sipCreateTypeNm': null, 'sipAllocExTypeCd': null, 'sipAllocExTypeNm': null, 'lvlMstSeqListVo': null, 'sllnum': '', 'ssubscnealias': null, 'ssubsclgipportdescription': null, 'sicisofficescode': null, 'sicisofficesname': null, 'sofficecode': '', 'sofficename': null, 'smodelname': null, 'ssubscmstip': null, 'svalidCheck': null, 'sconnAlias': null, 'nipAllocMstSeq': null, 'ssubscnnescode': '', 'ssubscnescode': null, 'sgatewayip': null, 'sneSrchTypeCd': null, 'sicisofficescodeNe': 'XXXXXX', 'ssubscnealiasNe': '', 'smodelnameNe': '', 'ssubscmstipNe': '', 'sssvcMgroupNm': null, 'ssvcLgroupNm': null, 'ssvcUseTypeNm': null, 'ssaid': '', 'scustName': null, 'sipAssignSubNm': null, 'llSrchTypeCd': 'llnum', 'sordernum': '', 'sregyn': null, 'slacpsid': null, 'ssvcUseTypeCd': null, 'sexPushYn': null, 'nticketActSeq': null, 'sipmsSvcNm': null, 'sneossDdYn': null, 'sfirstAddrGwip': null, 'slastAddrGwip': null, 'sAlcSrchTypeCd': null, 'nwhoisSeq': null, 'nroutingChkMstSeq': null, 'pifSerialIp': null, 'sanealias': null, 'samstip': null, 'saifname': null, 'salocationcode': null, 'salocationcodeNm': null, 'saofficescode': null, 'saofficescodeNm': null, 'sznealias': null, 'szmstip': null, 'szifname': null, 'szlocationcode': null, 'szlocationcodeNm': null, 'szofficescode': null, 'szofficescodeNm': null, 'sofficescodeSrch': null, 'snealiasSrch': null, 'smstipSrch': null, 'sifipSrch': null, 'slocationcodeNmSrch': null, 'sllnumSrch': null, 'pifSerialIpSrch': null, 'nipLinkMstSeq': null, 'sconnalias': null, 'sGubun': null, 'sNextHop': null, 'totalCount': 0, 'nsummaryCnt': '', 'snull0Yn': '', 'sintgrmYn': '', 'spageType': null, 'ssubscnealiasType': null, 'bUploadFlag': false, 'sassignTypeCds': null, 'sassignTypeCdMultiStr': '', 'sassignTypeMulti': null, 'ssvcGroupCdMultiStr': '', 'ssvcGroupCdMulti': null, 'ssubsclgipportip': null, 'ssubscrouterserialip': null }
  })
}

export function apiRequestModel(api, params) {
  return http({
    url: `${api.url}.model`,
    method: 'post',
    filePath: filePath,
    data: params
  })
}
export function apiRequestJson(api, params) {
  return http({
    url: `${api.url}.json`,
    method: 'post',
    filePath: filePath,
    data: params
  })
}
export function apiRequestOffice(urlPath, params, listName = 'selectOfficeList',) {
  return http({
    url: `${urlPath}/${listName}.json`,
    method: 'post',
    filePath: filePath,
    data: params
  })
}

window.apiTest = apiTest
window.apiTest2 = apiTest2

