server:
  port: 8096

logging:
  level:
    root: INFO
---
spring:
  profiles: dev

  rabbitmq:
    address: 116.89.186.194 #KOREN
    port: 5675
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectl

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineClearExchange: nia.exchangeEngineClearDirectly
    engineClearQueue: nia.EngineClearIndexDirectly
    engineClearRoutingKey: nia.EngineClearIndexDirectly

  kafka:
    consumer:
      bootstrap-servers: 210.114.91.190:9092
      group-id: pringData
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: 210.114.91.190:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
#    url: jdbc:postgresql://183.107.19.138:8000/niadb #집
    url: jdbc:postgresql://210.114.91.190:5433/codejdb #개발
    username: codej
    password: codej12!@
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: real

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
    address: 116.89.186.194 #KOREN
    port: 5675
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectl

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineClearExchange: nia.exchangeEngineClearDirectly
    engineClearQueue: nia.EngineClearIndexDirectly
    engineClearRoutingKey: nia.EngineClearIndexDirectly

  kafka:
    consumer:
      bootstrap-servers: 116.89.186.194:9092
      group-id: pringData
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 116.89.186.194:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://116.89.186.194:5433/niadb #KOREN
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize : 10
    idleTimeout : 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: codej

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
    address: 10.81.192.18
    port: 5672
    username: rcaadmin
    password: rcaadmin12#$

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectl

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineClearExchange: nia.exchangeEngineClearDirectly
    engineClearQueue: nia.EngineClearIndexDirectly
    engineClearRoutingKey: nia.EngineClearIndexDirectly

  kafka:
    consumer:
      bootstrap-servers: 116.89.186.194:9092
      group-id: pringData
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 116.89.186.194:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.81.192.18:5433/niadb #운영
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize : 10
    idleTimeout : 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true