server:
  port: 30301
logging:
  level:
    root: INFO  
    
---
spring:
  profiles: dev
  logging:
    config: classpath:context/logback-spring.xml

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  restTemplate:
      factory:
        readTimeout: 5000
        connectTimeout: 3000
      httpClient:
        maxConnTotal: 100
        maxConnPerRoute: 5

  ems:
    roadm_s_ip: 61.252.53.18
    roadm_d_ip: 61.252.53.34
    port_mmc: 42001
    port_evt: 42002
    id: ENC(AMpDRuUWdygDmaR9lJ9liQ==)
    pw: ENC(G/NSRIni6DQrjswCcJnUuXTOBI+pSnaS)

  nia:
    api:
      topology:
        url: http://45.248.75.202:8181/restconf/operational/network-topology:network-topology
        hearderName: authorization
        hearderValue: Basic YWRtaW46YWRtaW4=
      alarm-url: http://61.252.55.180:9200/tsdn_syslog/doc/
      performance-url: http://61.252.55.180:9200/tsdn_resource/doc/

  rabbitmq:
    address: 192.168.0.87  #개발
    port: 5675
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmLinkageSendExchange: nia.exchangeAlarmLinkageSendDirectly
    niaAlarmLinkageSendQueue: nia.AlarmLinkageSendIndexDirectly
    niaAlarmLinkageSendRoutingKey: AlarmLinkageSendIndexDirectly

    niaPerformanceToAiSendExchange: nia.exchangeNiaPerformanceToAiSendDirectly
    niaPerformanceToAiSendQueue: nia.NiaPerformanceToAiSendIndexDirectly
    niaPerformanceToAiSendRoutingKey: NiaPerformanceToAiSendIndexDirectly

    niaPerformanceFailExchange: nia.exchangeNiaPerformanceFailDirectly
    niaPerformanceFailQueue: nia.NiaPerformanceFailIndexDirectly
    niaPerformanceFailRoutingKey: NiaPerformanceFailIndexDirectly


  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://192.168.0.87:5433/niadb #개발
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize : 10
    idleTimeout : 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations: classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: home
  logging:
    config: classpath:context/logback-spring.xml

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  restTemplate:
    factory:
      readTimeout: 5000
      connectTimeout: 3000
    httpClient:
      maxConnTotal: 100
      maxConnPerRoute: 5

  ems:
    roadm_s_ip: 183.107.19.138
    roadm_d_ip: 183.107.19.138
    port_mmc: 8003
    port_evt: 8004
    id: ENC(AMpDRuUWdygDmaR9lJ9liQ==)
    pw: ENC(G/NSRIni6DQrjswCcJnUuXTOBI+pSnaS)

  nia:
    api:
      topology:
        url: http://45.248.75.202:8181/restconf/operational/network-topology:network-topology
        hearderName: authorization
        hearderValue: Basic YWRtaW46YWRtaW4=
      alarm-url: http://61.252.55.180:9200/tsdn_syslog/doc/
      performance-url: http://61.252.55.180:9200/tsdn_resource/doc/

  rabbitmq:
    address: 183.107.19.138  #개발
    port: 8001
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmLinkageSendExchange: nia.exchangeAlarmLinkageSendDirectly
    niaAlarmLinkageSendQueue: nia.AlarmLinkageSendIndexDirectly
    niaAlarmLinkageSendRoutingKey: AlarmLinkageSendIndexDirectly

    niaPerformanceToAiSendExchange: nia.exchangeNiaPerformanceToAiSendDirectly
    niaPerformanceToAiSendQueue: nia.NiaPerformanceToAiSendIndexDirectly
    niaPerformanceToAiSendRoutingKey: NiaPerformanceToAiSendIndexDirectly

    niaPerformanceFailExchange: nia.exchangeNiaPerformanceFailDirectly
    niaPerformanceFailQueue: nia.NiaPerformanceFailIndexDirectly
    niaPerformanceFailRoutingKey: NiaPerformanceFailIndexDirectly

  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://183.107.19.138:8000/niadb #개발
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize : 30
    idleTimeout : 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations: classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: real
  logging:
    config: classpath:logback-spring.xml

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  restTemplate:
      factory:
        readTimeout: 5000
        connectTimeout: 3000
      httpClient:
        maxConnTotal: 100
        maxConnPerRoute: 5

  ems:
    roadm_s_ip: 61.252.53.18
    roadm_d_ip: 61.252.53.34
    port_mmc: 42001
    port_evt: 42002
    id: ENC(AMpDRuUWdygDmaR9lJ9liQ==)
    pw: ENC(G/NSRIni6DQrjswCcJnUuXTOBI+pSnaS)

  nia:
    api:
      topology:
        url: http://45.248.75.202:8181/restconf/operational/network-topology:network-topology
        hearderName: authorization
        hearderValue: Basic YWRtaW46YWRtaW4=
      alarm-url: http://61.252.55.180:9200/tsdn_syslog/doc/
      performance-url: http://61.252.55.180:9200/tsdn_resource/doc/

  rabbitmq:
    address: 116.89.186.194
    port: 5675
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmLinkageSendExchange: nia.exchangeAlarmLinkageSendDirectly
    niaAlarmLinkageSendQueue: nia.AlarmLinkageSendIndexDirectly
    niaAlarmLinkageSendRoutingKey: AlarmLinkageSendIndexDirectly

    niaPerformanceToAiSendExchange: nia.exchangeNiaPerformanceToAiSendDirectly
    niaPerformanceToAiSendQueue: nia.NiaPerformanceToAiSendIndexDirectly
    niaPerformanceToAiSendRoutingKey: NiaPerformanceToAiSendIndexDirectly

    niaPerformanceFailExchange: nia.exchangeNiaPerformanceFailDirectly
    niaPerformanceFailQueue: nia.NiaPerformanceFailIndexDirectly
    niaPerformanceFailRoutingKey: NiaPerformanceFailIndexDirectly

  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://116.89.186.194:5433/niadb
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize : 10
    idleTimeout : 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations: classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true