version: '2'
services:
  frr:
    image: ipsdn_frr
    build: .
    container_name: "ipsdn_frr_1"
    hostname: "frr-pangyo"
    restart: always
    ports:
      - "179:179"
      - "22179:22"
    environment:
      FRR_DAEMONS: zebra
    tty: true
#    network_mode: "bridge"
    networks:
      frr_eth0:
       ipv4_address: 10.44.44.2
      frr:
       ipv4_address: 61.252.55.131
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
      - /root/.ssh:/root/.ssh:ro
networks:
    frr_eth0:
     external:
       name: frr_private
    frr:
     external:
       name: ipvlan_frr
