server:
  port: 8070
spring:
  config:
    import: "classpath:/properties/config.dev"
  profiles:
    active: dev
    dev: true

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  datasource2nd:
    enabled: true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://192.168.0.17:5444/ipms
    username: ipms_user
    password: new1234!
    mapper-packages: >
      com.kt.ipms.mapper.db2nd,
      com.kt.ipms.legacy

  sql:
    init:
      platform: postgres
      encoding: UTF-8

myconf:
  auth:
    use: false #auth.use
  encrypt: false 

file:
  # upload-dir: ./external
