server:
  port: 8070

spring:
  config:
    import: "classpath:/properties/config.dev"
  profiles:
    active: dev
    dev: true

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  sql:
    init:
      platform: postgres
      encoding: UTF-8

file:
  upload-dir: ./external
