server:
  port: 30406
logging:
  level:
    root: INFO  
    
---
spring:
  profiles: dev
  logging:
    config: classpath:logback-spring.xml

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )


  rabbitmq:
    address: 192.168.0.87  #개발
    port: 6786
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaIpAlarmExchange: nia.exchangeNiaIpAlarmDirectly
    niaIpAlarmQueue: nia.NiaIpAlarmIndexDirectly
    niaIpAlarmRoutingKey: nia.NiaIpAlarmIndexDirectl

  task:
    poolSize: 100 
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://116.89.186.194:5433/niadb
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations: classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

  ftp:
    host1: 116.89.186.206
    host2: 116.89.186.207
    #    host: 116.89.186.194
    port: 22
    user: ENC(XMOpjFUtgZnBRPp7m7a9o2WSXQ1l5oe/)
    password: ENC(Q5gydJpI5uME0zXRuMHImGC5bkFqmaRK)
    file-path: /home/zerooneai211202/data/
    nia-file-path: /home/zerooneai211202/data/

---
spring:
  profiles: real
  logging:
    config: classpath:logback-spring.xml

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
    address: 116.89.191.47
    port: 6786
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaIpAlarmExchange: nia.exchangeNiaIpAlarmDirectly
    niaIpAlarmQueue: nia.NiaIpAlarmIndexDirectly
    niaIpAlarmRoutingKey: nia.NiaIpAlarmIndexDirectl

  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://116.89.191.47:6544/niadb
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations: classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

  ftp:
    host1: 116.89.191.34
    host2: 116.89.191.35
    port: 16891
    user: ENC(XMOpjFUtgZnBRPp7m7a9o2WSXQ1l5oe/)
    password: ENC(Q5gydJpI5uME0zXRuMHImGC5bkFqmaRK)
    file-path: /home/zero1ai/data/

---
spring:
  profiles: codej
  logging:
    config: classpath:logback-spring.xml

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
    address: 10.81.192.18
    port: 5672
    username: rcaadmin
    password: rcaadmin12#$

    niaIpAlarmExchange: nia.exchangeNiaIpAlarmDirectly
    niaIpAlarmQueue: nia.NiaIpAlarmIndexDirectly
    niaIpAlarmRoutingKey: nia.NiaIpAlarmIndexDirectl

  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.81.192.18:5433/niadb #운영
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations: classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

  ftp:
    host1: 116.89.186.206
    host2: 116.89.186.207
    port: 11689
    user: zerooneai211202
    password: ZeroOneAi11!@#
    file-path: /home/zerooneai211202/data/