server:
  port: 8080
  servlet:
    context-path: 
    
spring:
  profiles:
    active: oper
    dev: false

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  datasource2nd:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(Z/0jxFEW33jQOjb7SJSDlY6IbaIG48G0VWQXw8WHNXRuL5iPonp+Uoy+8KdVgIibG1tAqGzFYMzKnlmGHroFXQ==)
    username: ENC(6H5QdS8FFUnUVecEEf9DlA==)
    password: ENC(5wuR7RSaFfNs5/sf/L74ufnWgg8Q3SRV)
    dataSource-name: datahub
    enabled: true


  sql:
    init:
      platform: postgres
      encoding: UTF-8

myconf:
  api-server:
    kong: ENC(84Z1sHnW4pQBxXR7c5HzCI9DFTJ8xjEtYKndkrpawU7rfYRK3JIF8g==) 
    kong-admin: ENC(rtySWfcTU78pXNqzPEvjpj7Ed54qivRLJIRvTHV9JmViFskT3ksDpA==) 
    kong-use: true
    grafana-url: ENC(xraTW2CYr0s+mWBJqMINIxaa7Xc6wBYLNhIpTD0OoF4+7zWpsJzx7YSEqdmhvP31)
    hub-api: ENC(wNxGQ47lJwguxyBJVKyg3epEQNBbnZHp2iJqOHxF4XaWh+40Ww6cKg==) 
  dhub:
    auth-url: ENC(miADMTitM56pXljUvTnxzItAK1ZNHO4NWy/7vr0L8d/nXEP9CmIt73YIshXki0NsM7cvVbO3AoI=)

file:
  upload-dir: ./external

