//created on: 2020. 09. 03
package potn

//list any import classes here.
import com.nia.engine.common.RcaAlarmType;
import com.nia.engine.common.RcaCodeInfo;
import com.nia.engine.common.RcaResultType;
import com.nia.engine.vo.BasicAlarmVo;
import com.nia.engine.vo.RcaResult;
import com.nia.engine.vo.ClusterObject;
import com.nia.engine.vo.Flag;

import java.util.List;
import java.util.Map;
import java.util.HashSet;
import java.util.ArrayList;
import java.sql.Timestamp;

//declare any global variables here
global RcaResult rcaResult;


rule "POTN_NODE_ISOLATION"
salience 1000
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_NODE_ISOLATION)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_NODE_ISOLATION");
        rcaResult.setFaultDetailCode("노드 고립");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CONTROL_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CONTROL_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_CONTROL_UNIT_OUT");
        rcaResult.setFaultDetailCode("제어부 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_UNIT_OUT");
        rcaResult.setFaultDetailCode("이더넷 UNI 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_FAN_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_FAN_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_FAN_UNIT_OUT");
        rcaResult.setFaultDetailCode("냉각팬 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LINK_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LINK_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LINK_UNIT_OUT");
        rcaResult.setFaultDetailCode("링크 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LOGIC_BOARD_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LOGIC_BOARD_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LOGIC_BOARD_OUT");
        rcaResult.setFaultDetailCode("논리 보드 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_UNIT_OUT");
        rcaResult.setFaultDetailCode("OTN NNI 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNIT_OUT");
        rcaResult.setFaultDetailCode("STM UNI 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SWITCH_FABRIC_UNIT_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SWITCH_FABRIC_UNIT_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SWITCH_FABRIC_UNIT_OUT");
        rcaResult.setFaultDetailCode("스위칭 유닛 탈장");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CONTROL_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CONTROL_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_CONTROL_UNIT_FAIL");
        rcaResult.setFaultDetailCode("제어부 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_UNIT_FAIL");
        rcaResult.setFaultDetailCode("이더넷 UNI 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_FAN_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_FAN_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_FAN_UNIT_FAIL");
        rcaResult.setFaultDetailCode("냉각팬 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end



rule "POTN_LINK_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LINK_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LINK_UNIT_FAIL");
        rcaResult.setFaultDetailCode("링크 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_UNIT_FAIL");
        rcaResult.setFaultDetailCode("OTN NNI 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SM_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SM_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SM_UNIT_FAIL");
        rcaResult.setFaultDetailCode("SM 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNIT_FAIL");
        rcaResult.setFaultDetailCode("STM UNI 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_UAS_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_UAS_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_UAS_UNIT_FAIL");
        rcaResult.setFaultDetailCode("UAS 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_PWR_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_PWR_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_PWR_FAIL");
        rcaResult.setFaultDetailCode("전원 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_POWER_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SWITCH_FABRIC_UNIT_FAIL"
salience 800
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SWITCH_FABRIC_UNIT_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SWITCH_FABRIC_UNIT_FAIL");
        rcaResult.setFaultDetailCode("스위칭 유닛 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_MPLS_PROT_SWITCH_LOCAL_REQ"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_MPLS_PROT_SWITCH_LOCAL_REQ)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_MPLS_PROT_SWITCH_LOCAL_REQ");
        rcaResult.setFaultDetailCode("MPLS 절체 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_MPLS_PROT_SWITCH_REMOTE_REQ"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_MPLS_PROT_SWITCH_REMOTE_REQ)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_MPLS_PROT_SWITCH_REMOTE_REQ");
        rcaResult.setFaultDetailCode("MPLS 절체 대항 노드 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end



rule "POTN_ETH_UNI_B_SF"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_UNI, alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.sysname, topology != null, topology.oppSysname == $a1.topology.oppSysname, slot != $a1.slot, alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOS)
        $a3 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_UNI_B_SF");
        rcaResult.setFaultDetailCode("이더넷 UNI 주/예비 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_NNI_B_SF"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.sysname, topology != null, topology.oppSysname == $a1.topology.oppSysname, slot != $a1.slot, alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOS)
        $a3 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_NNI_B_SF");
        rcaResult.setFaultDetailCode("OTN NNI 주/예비 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_NNI_B_SF"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.sysname, topology != null, topology.oppSysname == $a1.topology.oppSysname, slot != $a1.slot, alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOS)
        $a3 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_NNI_B_SF");
        rcaResult.setFaultDetailCode("ODU NNI 주/예비 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OCH_NNI_B_SF"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.sysname, topology != null, topology.oppSysname == $a1.topology.oppSysname, slot != $a1.slot, alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_LOS)
        $a3 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OCH_NNI_B_SF");
        rcaResult.setFaultDetailCode("OCH NNI 주/예비 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNI_B_SF"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_UNI, alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.sysname, topology != null, topology.oppSysname == $a1.topology.oppSysname, slot != $a1.slot, alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOS)
        $a3 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNI_B_SF");
        rcaResult.setFaultDetailCode("STM UNI 주/예비 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_WDM_NNI_B_SF"
salience 700
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.sysname, topology != null, topology.oppSysname == $a1.topology.oppSysname, slot != $a1.slot, alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_LOS)
        $a3 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_WDM_NNI_B_SF");
        rcaResult.setFaultDetailCode("WDN NNI 주/예비 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end



rule "POTN_ETH_UNI_SF_BI"
salience 600
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_UNI, alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_UNI_SF_BI");
        rcaResult.setFaultDetailCode("ETH UNI 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_NNI_SF_BI"
salience 600
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_NNI_SF_BI");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNI_SF_BI"
salience 600
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_UNI, alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNI_SF_BI");
        rcaResult.setFaultDetailCode("STM UNI 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_WDM_NNI_SF_BI"
salience 600
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_LOS)
        $a2 : BasicAlarmVo(sysname == $a1.topology.oppSysname, slot == $a1.topology.oppSlot, alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_WDM_NNI_SF_BI");
        rcaResult.setFaultDetailCode("WDM NNI 수신단 양방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        rcaResult.addRelatedAlarm($a2);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_PORT_15M_TCA_THRESHOLD_OVER"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_PORT_15M_TCA_THRESHOLD_OVER)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_PORT_15M_TCA_THRESHOLD_OVER");
        rcaResult.setFaultDetailCode("ETH PORT 15분 TCA임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_PORT_1D_TCA_THRESHOLD_OVER"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_PORT_1D_TCA_THRESHOLD_OVER)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_PORT_1D_TCA_THRESHOLD_OVER");
        rcaResult.setFaultDetailCode("ETH PORT 1D TCA임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ASON_OSPF_TCA"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ASON_OSPF_TCA)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ASON_OSPF_TCA");
        rcaResult.setFaultDetailCode("ASON OSPF 임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_BACKUP_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_BACKUP_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_BACKUP_FAIL");
        rcaResult.setFaultDetailCode("백업 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CONTROL_CHANNEL_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CONTROL_CHANNEL_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_CONTROL_CHANNEL_FAIL");
        rcaResult.setFaultDetailCode("제어부 채널 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CONTROL_UNIT_INIT"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CONTROL_UNIT_INIT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_CONTROL_UNIT_INIT");
        rcaResult.setFaultDetailCode("제어부 유닛 초기화");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CONTROL_UNIT_IPC_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CONTROL_UNIT_IPC_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_CONTROL_UNIT_IPC_FAIL");
        rcaResult.setFaultDetailCode("제어부-장비간 통신장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CPU_TCA"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CPU_TCA)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_CPU_TCA");
        rcaResult.setFaultDetailCode("CPU 임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_DCN_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_DCN_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_DCN_FAIL");
        rcaResult.setFaultDetailCode("DCN 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_GNE_CONNECT_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_GNE_CONNECT_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_GNE_CONNECT_FAIL");
        rcaResult.setFaultDetailCode("GNE 연결 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_IPC_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_IPC_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_IPC_FAIL");
        rcaResult.setFaultDetailCode("유닛-장비간 통신 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LOGIN_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LOGIN_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LOGIN_FAIL");
        rcaResult.setFaultDetailCode("로그인 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_FAIL");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 링크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_UNIT_IPC_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_UNIT_IPC_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_ODU_UNIT_IPC_FAIL");
        rcaResult.setFaultDetailCode("ODU NNI 유닛-장비간 통신장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_FAIL");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 링크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_UNIT_IPC_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_UNIT_IPC_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_OTN_UNIT_IPC_FAIL");
        rcaResult.setFaultDetailCode("OTN NNI 유닛-장비간 통신장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTU_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTU_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTU_FAIL");
        rcaResult.setFaultDetailCode("OTU NNI 수신단 링크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_UNI_SF_SI"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_UNI, alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_UNI_SF_SI");
        rcaResult.setFaultDetailCode("ETH UNI 수신단 단방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_NTP_CONNECTION_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_NTP_CONNECTION_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_NTP_CONNECTION_FAIL");
        rcaResult.setFaultDetailCode("NTP 서버 연결 실패");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_LOSS_OF_CLK"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOSS_OF_CLK)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_OTN_LOSS_OF_CLK");
        rcaResult.setFaultDetailCode("OTN NNI 유닛 클럭 싱크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_NNI_SF_SI"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_NNI_SF_SI");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 단방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_NNI_SF_SI"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_NNI_SF_SI");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 단방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OCH_NNI_SF_SI"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OCH_NNI_SF_SI");
        rcaResult.setFaultDetailCode("OCH NNI 수신단 단방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_RSVP_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_RSVP_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_RSVP_FAIL");
        rcaResult.setFaultDetailCode("RSVP 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SFPP_LOS"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SFPP_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SFPP_LOS");
        rcaResult.setFaultDetailCode("SFPP 신호 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_FAIL");
        rcaResult.setFaultDetailCode("STM UNI 수신단 링크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNIT_IPC_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_UNIT_IPC_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_STM_UNIT_IPC_FAIL");
        rcaResult.setFaultDetailCode("STM UNI 유닛-장비간 통신장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNI_SF_SI"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_UNI, alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNI_SF_SI");
        rcaResult.setFaultDetailCode("STM UNI 수신단 단방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_LOSS_OF_CLK"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOSS_OF_CLK)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_STM_LOSS_OF_CLK");
        rcaResult.setFaultDetailCode("STM UNI 유닛 클럭 싱크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SYNC_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SYNC_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_SYNC_FAIL");
        rcaResult.setFaultDetailCode("클럭 싱크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end



rule "POTN_SYNC_LOS"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SYNC_LOS)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_SYNC_LOS");
        rcaResult.setFaultDetailCode("클럭 싱크 신호 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_TE_LINK_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_TE_LINK_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_TE_LINK_FAIL");
        rcaResult.setFaultDetailCode("TE 링크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_SIGNAL_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_SIGNAL_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_SIGNAL_FAIL");
        rcaResult.setFaultDetailCode("VC3 링크 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC4_SIGNAL_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC4_SIGNAL_FAIL)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC4_SIGNAL_FAIL");
        rcaResult.setFaultDetailCode("VC4 링크 신호 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_WDM_NNI_SF_SI"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(topology != null, topology.nwType == RcaCodeInfo.TOPOLOGY_GB_NNI, alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_WDM_NNI_SF_SI");
        rcaResult.setFaultDetailCode("WDM NNI 수신단 단방향 링크장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_WDM_CLK_FAIL"
salience 500
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_CLK_FAIL)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_WDM_CLK_FAIL");
        rcaResult.setFaultDetailCode("WDM NNI 수신단 클럭 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_APS_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_APS_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_APS_ERR");
        rcaResult.setFaultDetailCode("APS 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_BUS_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_BUS_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_BUS_ERR");
        rcaResult.setFaultDetailCode("BUS 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_NODE_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_DATA_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_DATA_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_DATA_ERR");
        rcaResult.setFaultDetailCode("데이터 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_DCN_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_DCN_ERR)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_DCN_ERR");
        rcaResult.setFaultDetailCode("DCN 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_COMM_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_ERR");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 링크 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_UNIT_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_UNIT_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_UNIT_ERR");
        rcaResult.setFaultDetailCode("이더넷 UNI 유닛 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LOG_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LOG_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LOG_ERR");
        rcaResult.setFaultDetailCode("로그 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OCH_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OCH_ERR");
        rcaResult.setFaultDetailCode("OCH NNI 수신단 링크 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_ERR");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 링크 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_MSI_CONF_MISMATCH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_MSI_CONF_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_MSI_CONF_MISMATCH");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 MSI 설정 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OPTIC_TEMP_HIGH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OPTIC_TEMP_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OPTIC_TEMP_HIGH");
        rcaResult.setFaultDetailCode("광 모듈 고온 경보 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OSRP_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OSRP_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OSRP_ERR");
        rcaResult.setFaultDetailCode("OSRP 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_OPTIC_CONF_MISMATCH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_OPTIC_CONF_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_OPTIC_CONF_MISMATCH");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 광모듈 설정 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_UNIT_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_UNIT_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_UNIT_ERR");
        rcaResult.setFaultDetailCode("OTN NNI 유닛 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_UNIT_TEMP_HIGH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_UNIT_TEMP_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_UNIT_TEMP_HIGH");
        rcaResult.setFaultDetailCode("OTN NNI 유닛 고온 경보 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTU_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTU_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTU_ERR");
        rcaResult.setFaultDetailCode("OTU NNI 수신단 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_PASSWORD_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_PASSWORD_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_PASSWORD_ERR");
        rcaResult.setFaultDetailCode("패스워드 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CLK_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CLK_ERR)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_CLK_ERR");
        rcaResult.setFaultDetailCode("클럭 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SECURITY_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SECURITY_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SECURITY_ERR");
        rcaResult.setFaultDetailCode("보안 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SERVICE_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SERVICE_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SERVICE_ERR");
        rcaResult.setFaultDetailCode("서비스 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_CONF_MISMATCH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_CONF_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_CONF_MISMATCH");
        rcaResult.setFaultDetailCode("STM UNI 수신단 설정 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_ERR");
        rcaResult.setFaultDetailCode("STM UNI 수신단 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_MS_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_MS_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_MS_ERR");
        rcaResult.setFaultDetailCode("STM UNI 수신단 MS 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_OPTIC_CONF_MISMATCH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_OPTIC_CONF_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_OPTIC_CONF_MISMATCH");
        rcaResult.setFaultDetailCode("STM UNI 수신단 광모듈 설정 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNIT_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_UNIT_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNIT_ERR");
        rcaResult.setFaultDetailCode("STM UNI 유닛 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_UNIT_TEMP_HIGH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_UNIT_TEMP_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_UNIT_TEMP_HIGH");
        rcaResult.setFaultDetailCode("STM UNI 유닛 고온 경보 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SYNC_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SYNC_ERR)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_SYNC_ERR");
        rcaResult.setFaultDetailCode("클럭 싱크 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_TE_LINK_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_TE_LINK_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_TE_LINK_ERR");
        rcaResult.setFaultDetailCode("TE 링크 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_TUNNEL_ERR"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_TUNNEL_ERR)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_TUNNEL_ERR");
        rcaResult.setFaultDetailCode("터널 오류");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_WDM_OPTIC_CONF_MISMATCH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_OPTIC_CONF_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_WDM_OPTIC_CONF_MISMATCH");
        rcaResult.setFaultDetailCode("WDM NNI 수신단 광모듈 설정 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_WDM_UNIT_TEMP_HIGH"
salience 400
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_WDM_UNIT_TEMP_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_WDM_UNIT_TEMP_HIGH");
        rcaResult.setFaultDetailCode("WDM NNI 유닛 고온 경보 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_RX_PWR_HIGH"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_RX_PWR_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_RX_PWR_HIGH");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 광 세기 증가");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_RX_PWR_LOW"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_RX_PWR_LOW)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_RX_PWR_LOW");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 광 세기 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OCH_RX_PWR_HIGH"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_RX_PWR_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OCH_RX_PWR_HIGH");
        rcaResult.setFaultDetailCode("OCH NNI 수신단 광 세기 증가");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OCH_RX_PWR_LOW"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_RX_PWR_LOW)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OCH_RX_PWR_LOW");
        rcaResult.setFaultDetailCode("OCH NNI 수신단 광 세기 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_RX_PWR_HIGH"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_RX_PWR_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_RX_PWR_HIGH");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 광 세기 증가");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_RX_PWR_LOW"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_RX_PWR_LOW)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_RX_PWR_LOW");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 광 세기 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_RX_PWR_HIGH"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_RX_PWR_HIGH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_RX_PWR_HIGH");
        rcaResult.setFaultDetailCode("STM UNI 수신단 광 세기 증가");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_RX_PWR_LOW"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_RX_PWR_LOW)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_RX_PWR_LOW");
        rcaResult.setFaultDetailCode("STM UNI 수신단 광 세기 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_RX_PWR_LOW"
salience 300
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_RX_PWR_LOW)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_RX_PWR_LOW");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 광 세기 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_SD"
salience 250
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_SD)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_SD");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 신호 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_MS_SD"
salience 250
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_MS_SD)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_MS_SD");
        rcaResult.setFaultDetailCode("STM UNI 수신단 MS 신호 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_SD"
salience 250
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_SD)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_SD");
        rcaResult.setFaultDetailCode("STM UNI 수신단 신호 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end

// 200-100번대 룰은 파생 장애

rule "POTN_AU_AIS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_AU_AIS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_AU_AIS");
        rcaResult.setFaultDetailCode("AU AIS 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_AU_LOP"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_AU_LOP)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_AU_LOP");
        rcaResult.setFaultDetailCode("AU 포인터 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_AU_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_AU_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_AU_RDI");
        rcaResult.setFaultDetailCode("AU RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_FFI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_FFI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_FFI");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 FFI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_LFI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LFI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_LFI");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 LFI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_LOF");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_RDI");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_GFP_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_GFP_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_GFP_LOF");
        rcaResult.setFaultDetailCode("GFP 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LINK_BDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LINK_BDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LINK_BDI");
        rcaResult.setFaultDetailCode("링크 BDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LINK_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LINK_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LINK_LOF");
        rcaResult.setFaultDetailCode("링크 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LINK_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LINK_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LINK_RDI");
        rcaResult.setFaultDetailCode("링크 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OCH_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OCH_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OCH_LOF");
        rcaResult.setFaultDetailCode("OCH 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_AIS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_AIS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_AIS");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 AIS 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_BDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_BDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_BDI");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 BDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_CSF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_CSF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_CSF");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 CSF 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_LABEL_MISMATCH"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LABEL_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_LABEL_MISMATCH");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 라벨 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_LOCAL_FAULT"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOCAL_FAULT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_LOCAL_FAULT");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 로컬 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_LOCKED"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOCKED)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_LOCKED");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 잠김");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_UNIT_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_LOF");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_RDI");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_LFI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LFI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_LFI");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 LFI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_LOF");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTU_LOS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTU_LOS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTU_LOS");
        rcaResult.setFaultDetailCode("OTU NNI 수신단 신호 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTU_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTU_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTU_LOF");
        rcaResult.setFaultDetailCode("OTU NNI 수신단 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ADMIN_LOCKED"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ADMIN_LOCKED)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ADMIN_LOCKED");
        rcaResult.setFaultDetailCode("관리자 계정 잠김");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_APS_ADMIN_LOCKED"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_APS_ADMIN_LOCKED)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_APS_ADMIN_LOCKED");
        rcaResult.setFaultDetailCode("APS 관리자 계정 잠김");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_LFI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LFI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_LFI");
        rcaResult.setFaultDetailCode("STM UNI 수신단 LFI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_LOF"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOF)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_LOF");
        rcaResult.setFaultDetailCode("STM UNI 수신단 프레임 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_MS_AIS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_MS_AIS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_MS_AIS");
        rcaResult.setFaultDetailCode("STM UNI 수신단 MS AIS 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_RDI");
        rcaResult.setFaultDetailCode("STM UNI 수신단 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_TE_LINK_TCA"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_TE_LINK_TCA)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_TE_LINK_TCA");
        rcaResult.setFaultDetailCode("TE 링크 임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_PW_LOC"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_PW_LOC)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_PW_LOC");
        rcaResult.setFaultDetailCode("PW 연결 장애");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_TUNNEL_LOC"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_TUNNEL_LOC)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_TUNNEL_LOC");
        rcaResult.setFaultDetailCode("터널 연결 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_AIS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_AIS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_AIS");
        rcaResult.setFaultDetailCode("VC3 AIS 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_BER_TCA"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_BER_TCA)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_BER_TCA");
        rcaResult.setFaultDetailCode("VC3 BER 임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_LABEL_MISMATCH"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_LABEL_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_LABEL_MISMATCH");
        rcaResult.setFaultDetailCode("VC3 라벨 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_LO_BER_TCA"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_LO_BER_TCA)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_LO_BER_TCA");
        rcaResult.setFaultDetailCode("VC3 하위 신호 BER 임계치 초과");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_LO_LABEL_MISMATCH"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_LO_LABEL_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_LO_LABEL_MISMATCH");
        rcaResult.setFaultDetailCode("VC3 하위 신호 라벨 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_LO_NO_PAYLOAD"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_LO_NO_PAYLOAD)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_LO_NO_PAYLOAD");
        rcaResult.setFaultDetailCode("VC3 하위 신호 페이로드 없음");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_LO_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_LO_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_LO_RDI");
        rcaResult.setFaultDetailCode("VC3 하위 신호 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_LOP"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_LOP)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_LOP");
        rcaResult.setFaultDetailCode("VC3 포인터 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_RDI");
        rcaResult.setFaultDetailCode("VC3 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_SD"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_SD)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_SD");
        rcaResult.setFaultDetailCode("VC3 신호 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC3_TU_AIS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC3_TU_AIS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC3_TU_AIS");
        rcaResult.setFaultDetailCode("VC3 TU AIS 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC4_AIS"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC4_AIS)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC4_AIS");
        rcaResult.setFaultDetailCode("VC4 AIS 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC4_LABEL_MISMATCH"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC4_LABEL_MISMATCH)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC4_LABEL_MISMATCH");
        rcaResult.setFaultDetailCode("VC4 라벨 불일치");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC4_LOP"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC4_LOP)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC4_LOP");
        rcaResult.setFaultDetailCode("VC4 포인터 소실");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);
        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC4_RDI"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC4_RDI)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC4_RDI");
        rcaResult.setFaultDetailCode("VC4 RDI 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_VC4_SD"
salience 200
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_VC4_SD)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_VC4_SD");
        rcaResult.setFaultDetailCode("VC4 신호 감쇠");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_APS_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_APS_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_APS_EVENT");
        rcaResult.setFaultDetailCode("APS 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ETH_LOOPBACK"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ETH_LOOPBACK)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ETH_LOOPBACK");
        rcaResult.setFaultDetailCode("이더넷 UNI 수신단 루프백 테스트");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_LAG_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_LAG_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_LAG_EVENT");
        rcaResult.setFaultDetailCode("LAG 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_MSP_APS_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_MSP_APS_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_MSP_APS_EVENT");
        rcaResult.setFaultDetailCode("MSP APS 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_EVENT");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_LOOPBACK"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_LOOPBACK)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_LOOPBACK");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 루프백 테스트");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ODU_SNCP_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ODU_SNCP_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ODU_SNCP_EVENT");
        rcaResult.setFaultDetailCode("ODU NNI 수신단 SNCP 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_EVENT");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_OTN_LOOPBACK"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_OTN_LOOPBACK)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_OTN_LOOPBACK");
        rcaResult.setFaultDetailCode("OTN NNI 수신단 루프백 테스트");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_ADMIN_LOGIN"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_ADMIN_LOGIN)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_ADMIN_LOGIN");
        rcaResult.setFaultDetailCode("관리자 계정 로그인");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_CLK_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_CLK_EVENT)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_CLK_EVENT");
        rcaResult.setFaultDetailCode("클럭 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SNCP_APS_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SNCP_APS_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_SNCP_APS_EVENT");
        rcaResult.setFaultDetailCode("SNCP APS 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_LINKCUT);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_STM_LOOPBACK"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_STM_LOOPBACK)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_STM_LOOPBACK");
        rcaResult.setFaultDetailCode("STM UNI 수신단 루프백 테스트");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_SYNC_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_SYNC_EVENT)
    then
    	//actions
        rcaResult.setRcaResultCode("POTN_SYNC_EVENT");
        rcaResult.setFaultDetailCode("클럭 싱크 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_CLOCK_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "POTN_TEST_EVENT"
salience 100
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_POTN_TEST_EVENT)
    then
        //actions
        rcaResult.setRcaResultCode("POTN_TEST_EVENT");
        rcaResult.setFaultDetailCode("테스트 이벤트 발생");
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_ETC_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


