server:
  port: 8096

logging:
  level:
    root: INFO
---
spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
#    address: 183.107.19.138  #집
    address: 192.168.0.87  #개발
#    port: 8001
    port: 5675
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectl

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineClearExchange: nia.exchangeEngineClearDirectly
    engineClearQueue: nia.EngineClearIndexDirectly
    engineClearRoutingKey: nia.EngineClearIndexDirectly

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
#    url: jdbc:postgresql://183.107.19.138:8000/niadb #집
    url: jdbc:postgresql://192.168.0.87:5433/niadb #개발
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:context/mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: real
  main:
    allow-bean-definition-overriding: true

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
    address: 116.89.186.194  #개발
    port: 5675
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectl

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineClearExchange: nia.exchangeEngineClearDirectly
    engineClearQueue: nia.EngineClearIndexDirectly
    engineClearRoutingKey: nia.EngineClearIndexDirectly

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://116.89.186.194:5433/niadb #개발
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:context/mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: codej
  main:
    allow-bean-definition-overriding: true

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  rabbitmq:
    address: 10.81.192.18
    port: 5672
    username: rcaadmin
    password: rcaadmin12#$

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectl

    clusterExchange: nia.exchangeClusterDirectly
    clusterQueue: nia.ClusterIndexDirectly
    clusterRoutingKey: nia.ClusterIndexDirectly

    engineClearExchange: nia.exchangeEngineClearDirectly
    engineClearQueue: nia.EngineClearIndexDirectly
    engineClearRoutingKey: nia.EngineClearIndexDirectly

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://10.81.192.18:5433/niadb #운영
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:context/mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true