server:
  port: 8080
  servlet:
    context-path: 
  
spring:
  profiles:
    active: test
    dev: false

  datasource2nd:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(UXGRvr/LfDzJ07K6bscashjghvY08lnMFk9F4dRsqeQdIdRb5gT6bQlx1My3panNO+v2wQFPtUS9R4khfRu76g==)
    username: ENC(dF2qMl+R9Hkl5UuvpLeI8A==)
    password: ENC(jJyszOsTmqoyuMkPlzgWbyFotJjXFd2l)
    dataSource-name: datahub
    enabled: true

myconf:
  api-server:
    kong: ENC(173EW0yHdlVH8VklUPG9QAZj4JsFD9o3FQqUfZQzLLyMIaVclwcvRg==)
    kong-admin: ENC(cSZ4X9TtIm5vEIf4B/3OrM7qjbAwaauXIH5xHRtV5468EWw/mFAzPw==)
    kong-use: false
    grafana-url: ENC(3aOJbgZwCMg1LQkyI5A1wTTDgwn7HI1p0TGa3u1Lx/9+2kW1xOLotndGhY+wYGZb)
    hub-api: ENC(dKLcXlP1shikUiEWZJRzM5Fa3eEPmKSxGC60dmaI3xHROGdsXvkxHQ==) 
  dhub:
    auth-url: ENC(dW6tv/zW2U7ep0O/uZzvXu3W45BaQFkmmGRvCu2C1Ir7ynrzh0CmFpQCfJ/JT1eBjNzxsmP3MQ0=)
    
file:
  upload-dir: ./external

