server:
  port: 8085

logging:
  level:
    root: INFO  
    
---
spring:
  profiles: dev
  rabbitmq:
    address: 192.168.0.87  #개발
    port: 6786
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectly

    niaTicketReStartExchange: nia.exchangeNiaTicketReStartDirectly
    niaTicketReStartQueue: nia.NiaTicketReStartIndexDirectly
    niaTicketReStartRoutingKey: nia.NiaTicketReStartIndexDirectly

    niaPerformanceExchange: nia.exchangeNiaPerformanceDirectly
    niaPerformanceQueue: nia.NiaPerformanceIndexDirectly
    niaPerformanceRoutingKey: NiaPerformanceIndexDirectly

    niaPerformanceToAiSendExchange: nia.exchangeNiaPerformanceToAiSendDirectly
    niaPerformanceToAiSendQueue: nia.NiaPerformanceToAiSendIndexDirectly
    niaPerformanceToAiSendRoutingKey: NiaPerformanceToAiSendIndexDirectly

    uiToEngineExchange: rca.exchangeUiToEngineDirectly
    uiToEngineQueue: rca.UiToEngineIndexDirectly
    uiToEngineRoutingKey: UiToEngineIndexDirectly


  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://192.168.0.87:5433/niadb #개발
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 3
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration: 
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: real
  rabbitmq:
    address: 116.89.186.194  #운영
    port: 6786
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)

    niaAlarmExchange: nia.exchangeNiaAlarmDirectly
    niaAlarmQueue: nia.NiaAlarmIndexDirectly
    niaAlarmRoutingKey: nia.NiaAlarmIndexDirectly

    niaTicketReStartExchange: nia.exchangeNiaTicketReStartDirectly
    niaTicketReStartQueue: nia.NiaTicketReStartIndexDirectly
    niaTicketReStartRoutingKey: nia.NiaTicketReStartIndexDirectly

    niaPerformanceExchange: nia.exchangeNiaPerformanceDirectly
    niaPerformanceQueue: nia.NiaPerformanceIndexDirectly
    niaPerformanceRoutingKey: NiaPerformanceIndexDirectly

    niaPerformanceToAiSendExchange: nia.exchangeNiaPerformanceToAiSendDirectly
    niaPerformanceToAiSendQueue: nia.NiaPerformanceToAiSendIndexDirectly
    niaPerformanceToAiSendRoutingKey: NiaPerformanceToAiSendIndexDirectly

    uiToEngineExchange: rca.exchangeUiToEngineDirectly
    uiToEngineQueue: rca.UiToEngineIndexDirectly
    uiToEngineRoutingKey: UiToEngineIndexDirectly

  task:
    poolSize: 100
    keepAlive: 600000
    queueCapacity: 100
    concurrency: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://116.89.186.194:5433/niadb #운영
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 3
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true
    