[rca]
http.server.port=8080
https.server.port=8081

# HTTPS KeyStore
keystore.file.path=config/rca.jks
keystore.password=rca1234

web.path=app/websrc
web.compression.supported=true

db.url=jdbc:postgresql://10.214.35.248:5433/
db.driver=org.postgresql.Driver
db.poolmax=1000
db.username=neuro
db.password=neuro123


