#server:
#  port: 30408

logging:
  level:
    root: INFO
---
spring:
  profiles: local

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  kafka:
    consumer:
      bootstrap-servers: 192.168.10.6:9392
      group-id: sflowData
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: 192.168.10.6:9392
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.10.6:5433/niadb
    username: niaadmin
    password: niaadmin12
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: dev

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  kafka:
    consumer:
      bootstrap-servers: 192.168.10.6:9392
      group-id: sflowData
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: 192.168.10.6:9392
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.10.6:5433/niadb
    username: niaadmin
    password: niaadmin12
    maximumPoolSize : 10
    idleTimeout : 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true

---
spring:
  profiles: real

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      property:
        prefix: ENC(
        suffix: )

  kafka:
    consumer:
      bootstrap-servers: 116.89.191.47:9392
      group-id: sflowData
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-interval-ms: 500000
    producer:
      bootstrap-servers: 116.89.191.47:9392
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://116.89.191.47:6544/niadb
    username: ENC(nM5TfLkdI8K26jnQlPUqUfRff1FyTWQG)
    password: ENC(y53jmhEna1ehHnCzMIn7gnMy7aDI0qiQ)
    maximumPoolSize: 10
    idleTimeout: 6000

  mybatis:
    mapper-locations: classpath*:sqlmap/*.xml
    mybatisConfig-locations : classpath:mybatis-config.xml
    configuration:
      mapUnderscoreToCamelCase: true
