name: CI/CD Pipeline

# 수동으로 워크플로우를 트리거하기 위해 'workflow_dispatch' 이벤트를 사용합니다.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     # node-version: '22.4.0'

      # - name: Install npm 
      #   run: npm install -g npm@9.6.7

      # - name: Build FE
      #   run: |
      #     cd FE
      #     npm install --force 
      #     npm run build:ipms
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'  

      # - name: Install Gradle
      #   run: |
      #     wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
      #     unzip gradle-7.6-bin.zip
      #     sudo mv gradle-7.6 /opt/gradle
      #     sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle

      - name: Verify Gradle installation
        run: gradle -v

      - name: Build BE
        run: |
          cd BE/app-ipms
          gradle bootJar

      - name: Build Docker images
        run: docker-compose build

      - name: Deploy services
        run: docker-compose up -d
