package switchs

//list any import classes here.
import com.nia.engine.common.RcaAlarmType;
import com.nia.engine.common.RcaCodeInfo;
import com.nia.engine.common.RcaResultType;
import com.nia.engine.vo.BasicAlarmVo;
import com.nia.engine.vo.RcaResult;
import com.nia.engine.vo.ClusterObject;
import com.nia.engine.vo.Flag;

import java.util.List;
import java.util.Map;
import java.util.HashSet;
import java.util.ArrayList;
import java.sql.Timestamp;

//declare any global variables here
global RcaResult rcaResult;


rule "SWITCH_PING_UNREACHABLE"
salience 1000
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_SWITCH_PING_UNREACHABLE)
    then
        //actions
        rcaResult.setRcaResultCode("SWITCH_PING_UNREACHABLE");
        rcaResult.setFaultDetailCode("PING 통신 장애");
        rcaResult.setDomainCode(RcaCodeInfo.DOMAIN_SWITCH);
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_SWITCH_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "SWITCH_SNMP_TIME_OUT"
salience 900
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_SWITCH_SNMP_TIME_OUT)
    then
        //actions
        rcaResult.setRcaResultCode("SWITCH_SNMP_TIME_OUT");
        rcaResult.setFaultDetailCode("SNMP 통신 장애");
        rcaResult.setDomainCode(RcaCodeInfo.DOMAIN_SWITCH);
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_SWITCH_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end


rule "SWITCH_PORT_DOWN"
salience 1000
lock-on-active
no-loop
    when
        //conditions
        flagTF : Flag(flag == false)
        $a1 : BasicAlarmVo(alarmmsg == RcaCodeInfo.ALARM_SWITCH_PORT_DOWN)
    then
        //actions
        rcaResult.setRcaResultCode("SWITCH_PORT_DOWN");
        rcaResult.setFaultDetailCode("PORT 다운");
        rcaResult.setDomainCode(RcaCodeInfo.DOMAIN_SWITCH);
        rcaResult.setRcaResultTypeCode(RcaCodeInfo.RCA_RESULT_SWITCH_FAIL);
        rcaResult.addRelatedAlarm($a1);

        flagTF.setFlag(true);
        update(flagTF);
end

