server:
  port: 8080
  servlet:
    context-path: /nia/portal

    
spring:
  profiles:
    active: oper
    dev: false

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  sql:
    init:
      platform: postgres
      encoding: UTF-8

  rabbitmq:
    enabled: true  

myconf:

file:
  upload-dir: ./external

