server:
  port: 8070
  servlet:
    context-path:
    
  
spring:
  profiles:
    active: test
    dev: false

  datasource2nd:
    # url: jdbc:log4jdbc:postgresql://incodej-lab.iptime.org:41544/niadb?allowMultiQueries=true
    # username: ENC(nEDs/lC9Tk5WpCugaKnCO2HbY1b88bnH)
    # password: ENC(aDtzf6fHV2dJdOeI5IWQ+C3vz3ly6Klm)
  rabbitmq:
    enabled: true # 접속 불가 환경을 위해 추가함
    address: incodej-lab.iptime.org
    port: 41072
    username: niaadmin
    password: niaadmin12#$
    niaEngineToUi: TEST_MQ_Queue1 # 2024.05.20 운영서버 알람을 가져오지 않기 위한 임시 설정

myconf:
  api-server:
    
file:
  upload-dir: ./external

