spring:
  profiles:
    active: dev
    dev: true

  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  sql:
    init:
      platform: postgres
      encoding: UTF-8

myconf:
  api-server:
  aimonitor-Url: http://incodej-lab.iptime.org:82
  servermonitor-Url: http://116.89.191.40:3000
  snapshot-Url: http://incodej-lab.iptime.org:24888/download/

file:
  upload-dir: ./external


