server:
  port: 8090
  
spring:
  profiles:
    active: dev
    dev: false

  datasource2nd:
    enabled: true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://192.168.0.241:6544/niadb?allowMultiQueries=true
    username: postgres
    password: zhemwpdl12!@
    dataSource-name: niadb
    mapper-packages: >
      com.codej.nia.mapper.db2nd,
      com.codej.nia.test.dao,

  rabbitmq:
    enabled: true 
    address: 192.168.0.241
    port: 5672
    username: niaadmin
    password: niaadmin12#$
    niaEngineToUi: nia.EngineToUiIndexDirectly
    niaUiToEngine: nia.UiToEngineIndexDirectly

